"""setup migrations

Revision ID: 4ee12ce8fdf0
Revises: 
Create Date: 2026-03-29 21:41:26.444607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ee12ce8fdf0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('med_cards',
    sa.Column('med_card_id', sa.Integer(), nullable=False),
    sa.Column('medcard_name', sa.String(), nullable=False),
    sa.Column('med_card_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('med_card_id', name=op.f('pk_med_cards'))
    )
    op.create_table('users',
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('sex', sa.String(), nullable=False),
    sa.Column('birth_date', sa.String(), nullable=False),
    sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_status', sa.String(), nullable=False),
    sa.Column('user_account_status', sa.String(), nullable=False),
    sa.Column('user_roles', sa.String(), nullable=False),
    sa.Column('telegram_tag', sa.String(), nullable=True),
    sa.Column('telegram_link', sa.String(), sa.Computed("'https://t.me/' || telegram_tag", ), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_uuid', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('user_med_cards',
    sa.Column('user_med_card_id', sa.Integer(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('med_card_id', sa.Integer(), nullable=False),
    sa.Column('med_card_created', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['med_card_id'], ['med_cards.med_card_id'], name=op.f('fk_user_med_cards_med_card_id_med_cards')),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.user_uuid'], name=op.f('fk_user_med_cards_user_uuid_users')),
    sa.PrimaryKeyConstraint('user_med_card_id', name=op.f('pk_user_med_cards'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_med_cards')
    op.drop_table('users')
    op.drop_table('med_cards')
    # ### end Alembic commands ###
