"""fead: add MedCard, modifyed User

Revision ID: ff61644e712a
Revises: 28227dcc2a35
Create Date: 2026-03-29 21:24:04.896072

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ff61644e712a"
down_revision: Union[str, Sequence[str], None] = "28227dcc2a35"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "med_cards",
        sa.Column("med_card_id", sa.Integer(), nullable=False),
        sa.Column("medcard_name", sa.String(), nullable=False),
        sa.Column("med_card_type", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("med_card_id", name=op.f("pk_med_cards")),
    )
    op.add_column("users", sa.Column("user_uuid", sa.UUID(), nullable=False))
    op.add_column("users", sa.Column("user_status", sa.String(), nullable=False))
    op.add_column(
        "users", sa.Column("user_account_status", sa.String(), nullable=False)
    )
    op.add_column("users", sa.Column("user_roles", sa.String(), nullable=False))
    op.add_column("users", sa.Column("telegram_tag", sa.String(), nullable=True))
    op.add_column(
        "users",
        sa.Column(
            "telegram_link",
            sa.String(),
            sa.Computed(
                "'https://t.me/' || telegram_tag",
            ),
            nullable=True,
        ),
    )
    op.alter_column("users", "username", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_constraint(op.f("users_username_key"), "users", type_="unique")
    op.create_unique_constraint(op.f("uq_users_username"), "users", ["username"])
    op.drop_column("users", "user_id")
    op.drop_column("users", "account_status")
    op.drop_column("users", "med_cars")
    op.create_table(
        "user_med_cards",
        sa.Column("user_med_card_id", sa.Integer(), nullable=False),
        sa.Column("user_uuid", sa.UUID(), nullable=False),
        sa.Column("med_card_id", sa.Integer(), nullable=False),
        sa.Column("med_card_created", sa.Date(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["med_card_id"],
            ["med_cards.med_card_id"],
            name=op.f("fk_user_med_cards_med_card_id_med_cards"),
        ),
        sa.ForeignKeyConstraint(
            ["user_uuid"],
            ["users.user_uuid"],
            name=op.f("fk_user_med_cards_user_uuid_users"),
        ),
        sa.PrimaryKeyConstraint("user_med_card_id", name=op.f("pk_user_med_cards")),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "med_cars",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column("account_status", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "users", sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(op.f("uq_users_username"), "users", type_="unique")
    op.create_unique_constraint(
        op.f("users_username_key"),
        "users",
        ["username"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column("users", "username", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("users", "telegram_link")
    op.drop_column("users", "telegram_tag")
    op.drop_column("users", "user_roles")
    op.drop_column("users", "user_account_status")
    op.drop_column("users", "user_status")
    op.drop_column("users", "user_uuid")
    op.drop_table("user_med_cards")
    op.drop_table("med_cards")
    # ### end Alembic commands ###
